// ====================================================
// AlitaOnHeightfield Landscape
// Initial source by René Lindsay
//
// The actor was downloaded from www.polycount.com
// The heightfied and texture was generated by Terragen
//          (see http://www.terragen.de/index.htm)
// ====================================================

program AlitaOnHeightfield;

uses
  Forms,
  Main in 'Main.pas' {FormMain};

{$R *.RES}

begin
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
