(*
  ai.planet
  http://aiplanet.sourceforge.net
  The original creator by Dave Kerr
*)
program AIPlanet;

uses
  Forms,
  cAIBaseObject in '..\Code\cAIBaseObject.pas',
  cAIBird in '..\Code\cAIBird.pas',
  cAIBot in '..\Code\cAIBot.pas',
  cAICoordinates in '..\Code\cAICoordinates.pas',
  cAICrab in '..\Code\cAICrab.pas',
  cAICreature in '..\Code\cAICreature.pas',
  cAIEnvironment in '..\Code\cAIEnvironment.pas',
  cAIEnvironmentStructures in '..\Code\cAIEnvironmentStructures.pas',
  cAIExplosions in '..\Code\cAIExplosions.pas',
  cAIFish in '..\Code\cAIFish.pas',
  cAIForce in '..\Code\cAIForce.pas',
  cAIFox in '..\Code\cAIFox.pas',
  cAIGrass in '..\Code\cAIGrass.pas',
  cAIGrazer in '..\Code\cAIGrazer.pas',
  cAIGrid in '..\Code\cAIGrid.pas',
  cAIHawk in '..\Code\cAIHawk.pas',
  cAILife in '..\Code\cAILife.pas',
  cAILink in '..\Code\cAILink.pas',
  cAIPosition in '..\Code\cAIPosition.pas',
  cAIRabbit in '..\Code\cAIRabbit.pas',
  cAIReality in '..\Code\cAIReality.pas',
  cAISatellites in '..\Code\cAISatellites.pas',
  cAIShark in '..\Code\cAIShark.pas',
  cAISpace in '..\Code\cAISpace.pas',
  cAITerrier in '..\Code\cAITerrier.pas',
  cAIThingReferenceList in '..\Code\cAIThingReferenceList.pas',
  cAIThings in '..\Code\cAIThings.pas',
  cAITool in '..\Code\cAITool.pas',
  cAITrees in '..\Code\cAITrees.pas',
  cAITrex in '..\Code\cAITrex.pas',
  cAITurtle in '..\Code\cAITurtle.pas',
  cAIVibes in '..\Code\cAIVibes.pas',
  cAIWeather in '..\Code\cAIWeather.pas',
  cGlobals in '..\Code\cGlobals.pas',
  cUserSettings in '..\Code\cUserSettings.pas',
  cUtilities in '..\Code\cUtilities.pas',
  f3DEnvironment in '..\Interface\f3DEnvironment.pas' {fm3DEnvironment},
  fAbout in '..\Interface\fAbout.pas' {fmAbout},
  fBuildProgress in '..\Interface\fBuildProgress.pas' {fmBuildProgress},
  fConstruction in '..\Interface\fConstruction.pas' {fmConstruction},
  fCreatingGalaxy in '..\Interface\fCreatingGalaxy.pas' {fmCreatingGalaxy},
  fEditLine in '..\Interface\fEditLine.pas' {,
  fEvents in '..\Interface\fEvents.pas' {fmEvents},
  fEvents in '..\Interface\fEvents.pas' {fmEvents},
  fImages in '..\Interface\fImages.pas' {fmImages},
  fIntro in '..\Interface\fIntro.pas' {fmIntro},
  fKeyboard in '..\Interface\fKeyboard.pas' {fmKeyboard},
  fLists in '..\Interface\fLists.pas' {fmLists},
  fManager in '..\Interface\fManager.pas' {fmManager},
  fMaximums in '..\Interface\fMaximums.pas' {fmMaximums},
  fMiniForm in '..\Interface\fMiniForm.pas',
  fNewReality in '..\Interface\fNewReality.pas' {fmNewReality},
  fPhotograph in '..\Interface\fPhotograph.pas' {fmPhotograph},
  fPlanet in '..\Interface\fPlanet.pas' {fmPlanet},
  fReality in '..\Interface\fReality.pas' {fmReality},
  fSatellite in '..\Interface\fSatellite.pas' {fmSatellite},
  fSettings in '..\Interface\fSettings.pas' {fmSettings},
  fSpirit in '..\Interface\fSpirit.pas',
  fTutorial in '..\Interface\fTutorial.pas',
  vInterfaceClasses in '..\Interface\vInterfaceClasses.pas',
  fFirstForm in '..\Interface\fFirstForm.pas' {fmFirstForm},
  vSpiritManager in '..\Interface\vSpiritManager.pas',
  vSplashScreen in '..\Interface\vSplashScreen.pas',
  cAIMouse in '..\Code\cAIMouse.pas',
  cAITiger in '..\Code\cAITiger.pas',
  cAIDuck in '..\Code\cAIDuck.pas',
  cAICommunity in '..\Code\cAICommunity.pas',
  fPopulations in '..\Interface\fPopulations.pas' {fmPopulations},
  cAIMating in '..\Code\cAIMating.pas',
  fHeightField in '..\Interface\fHeightField.pas' {fmHeightField},
  fHumidityMap in '..\Interface\fHumidityMap.pas' {fmHumidityMap},
  cAIDolphin in '..\Code\cAIDolphin.pas',
  cAIReportCard in '..\Code\cAIReportCard.pas',
  cAILadybug in '..\Code\cAILadybug.pas',
  cAIAnt in '..\Code\cAIAnt.pas',
  cAILearningCreature in '..\Code\cAILearningCreature.pas',
  cAIDNA in '..\Code\cAIDNA.pas',
  cAIGeneticCreature in '..\Code\cAIGeneticCreature.pas',
  fPosition in '..\Interface\fPosition.pas',
  fDNA in '..\Interface\fDNA.pas',
  cAIEvolvingTrees in '..\Code\cAIEvolvingTrees.pas',
  cAIMatingSingle in '..\Code\cAIMatingSingle.pas',
  fError in '..\Interface\fError.pas',
  frmTip in '..\Interface\frmTip.pas',
  cAIFireTree in '..\Code\cAIFireTree.pas',
  cAIMissileDefence in '..\Code\cAIMissileDefence.pas',
  fSplash in '..\Interface\fSplash.pas' {fmSplash};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Artificial Planet';
  Application.CreateForm(TfmFirstForm, fmFirstForm);
  Application.CreateForm(TfmImages, fmImages);
  Application.CreateForm(TfmSplash, fmSplash);
  Application.Run;
end.
